# Generated by Django 5.2.17 on 2026-09-29 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(blank=True, help_text='Leave empty to use AI_API_BASE_URL from .env', max_length=500)),
                ('timeout', models.PositiveIntegerField(default=120)),
                ('default_max_length', models.PositiveIntegerField(default=128)),
                ('default_min_length', models.PositiveIntegerField(default=20)),
                ('default_num_beams', models.PositiveIntegerField(default=4)),
                ('default_length_penalty', models.FloatField(default=1.0)),
                ('default_repetition_penalty', models.FloatField(default=1.2)),
                ('default_no_repeat_ngram_size', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI model configuration',
                'verbose_name_plural': 'AI model configuration',
            },
        ),
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=100)),
                ('method', models.CharField(default='POST', max_length=8)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(db_index=True, default=False)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('single', 'Single'), ('batch', 'Batch')], default='single', max_length=10)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('source_type', models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=10)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('input_text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('input_words', models.PositiveIntegerField(default=0)),
                ('summary_words', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('token_stats', models.JSONField(blank=True, default=dict)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
